//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _INTERFACELIBRARY_H_
#define _INTERFACELIBRARY_H_

#include <TinyCLR_Interop.h>
struct Library_InterfaceLibrary_SamrkashBT_Bluetooth
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__VOID__U4__U4);
    TINYCLR_NATIVE_DECLARE(Send___STATIC__BOOLEAN__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Recieve___STATIC__BOOLEAN__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SamrkashBT;

#endif  //_INTERFACELIBRARY_H_
