//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "InterfaceLibrary.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_InterfaceLibrary_SamrkashBT_Bluetooth::Init___STATIC__VOID__U4__U4,
    Library_InterfaceLibrary_SamrkashBT_Bluetooth::Send___STATIC__BOOLEAN__SZARRAY_U1,
    Library_InterfaceLibrary_SamrkashBT_Bluetooth::Recieve___STATIC__BOOLEAN__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SamrkashBT =
{
    "SamrkashBT", 
    0xEF90E0B5,
    method_lookup
};

