//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_EMOTE_NET_ROUTING_H_
#define _SAMRAKSH_EMOTE_NET_ROUTING_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_eMote_Net_Routing_Samraksh_eMote_Net_Routing_RoutingLayer
{
    static const int FIELD_STATIC___isRootNode = 0;

    TINYCLR_NATIVE_DECLARE(SendRoutingData___STATIC__I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(InitializeRouting___STATIC__I4__SZARRAY_U1__U2__I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_Net_Routing;

#endif  //_SAMRAKSH_EMOTE_NET_ROUTING_H_
