//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_SPOT.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::CreateDataStore___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::CreateData___I4__U4__U1,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::CreateData___I4__U4__U2,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::CreateData___I4__U4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetDataID___U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetUsedKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetFreeKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetReadAllDataIds___BOOLEAN__SZARRAY_I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetCountOfDataIds___U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Delete___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Write___BOOLEAN__U4__SZARRAY_U1__U4__U4__U1__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Write___BOOLEAN__U4__SZARRAY_U1__U4__U4__U2__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Write___BOOLEAN__U4__SZARRAY_U1__U4__U4__U4__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Read___BOOLEAN__U4__SZARRAY_U1__U4__U4__U1__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Read___BOOLEAN__U4__SZARRAY_U1__U4__U4__U2__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Read___BOOLEAN__U4__SZARRAY_U1__U4__U4__U4__I4,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::DeleteAll___STATIC__BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::EraseAllBlocks___STATIC__BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::DataStoreGC___STATIC__BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetReadWriteStatus___STATIC__BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetLastErrorStatus___STATIC__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::GetUsedKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::GetFreeKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::IsGCSamExtensionsEnabled___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::EnableIncrementalCleaning___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::EnableIncrementalCompaction___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::DisableIncrementalCleaning___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::DisableIncrementalCompaction___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanBeforeSleep___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanNow___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanNow___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::AvgTimeForCleaning___U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::AvgTimeForCompaction___U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_Data::LookupData___I4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_Data::LookupDataType___U4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_Data::LookupSize___U4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_Data::DeleteData___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_Data::ConstructNativeMemoryPointer___U4__U4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_Data::DisposeNativeMemoryPointer___BOOLEAN__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT =
{
    "Samraksh_SPOT", 
    0x89659C2C,
    method_lookup
};

