//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_SPOT.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::GetUsedKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::GetFreeKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::IsGCSamExtensionsEnabled___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::EnableIncrementalCleaning___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::EnableIncrementalCompaction___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::DisableIncrementalCleaning___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::DisableIncrementalCompaction___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanBeforeSleep___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanNow___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanNow___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::AvgTimeForCleaning___U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::AvgTimeForCompaction___U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::GetDataReference___I4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::LookupDataType___I4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::LookupDataSize___I4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::DeleteData___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::CreateData___I4__U4__U1,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::CreateData___I4__U4__U2,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::CreateData___I4__U4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::GetDataID___U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataReference::DisposeNativeMemoryPointer___BOOLEAN__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::CreateDataStore___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetMaxAllocationSize___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetTotalSpace___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetUsedBytes___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetFreeBytes___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetReadAllDataIds___I4__SZARRAY_I4__I4__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetCountOfDataIds___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::DeleteAll___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::EraseAllBlocks___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::DataStoreGC___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetReadWriteStatus___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetLastErrorStatus___I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Write___I4__U4__SZARRAY_U1__U4__U4__U1__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Write___I4__U4__SZARRAY_U1__U4__U4__U2__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Write___I4__U4__SZARRAY_U1__U4__U4__U4__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Read___I4__U4__SZARRAY_U1__U4__U4__U1__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Read___I4__U4__SZARRAY_U1__U4__U4__U2__I4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Read___I4__U4__SZARRAY_U1__U4__U4__U4__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT =
{
    "Samraksh_SPOT", 
    0x189D6DAB,
    method_lookup
};

