//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_SPOT.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::GetUsedKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::GetFreeKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::IsGCSamExtensionsEnabled___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::EnableIncrementalCleaning___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::EnableIncrementalCompaction___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::DisableIncrementalCleaning___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::DisableIncrementalCompaction___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanBeforeSleep___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanNow___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::CleanNow___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::AvgTimeForMarkAndSweep___U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_GC::AvgTimeForCompaction___U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetNumberOfDataRecords___U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Read___I4__U4__SZARRAY_U1,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::ReadAllDataIDs___U2__SZARRAY_U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Delete___BOOLEAN__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::DeleteAll___BOOLEAN,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::ConstructNativeMemoryPointer___U4__U4__U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetUsedKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::GetFreeKBytes___R4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::Write___I4__U4__SZARRAY_U1__BYREF_U4,
    Library_Samraksh_SPOT_Samraksh_SPOT_NonVolatileMemory_DataStore::DisposeNativeMemoryPointer___BOOLEAN__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT =
{
    "Samraksh_SPOT", 
    0x1D3BEB72,
    method_lookup
};

