//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "InterfaceLibrary.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_InterfaceLibrary_Samraksh_SPOT_ADCInternal::Init___STATIC__I4__I4,
    Library_InterfaceLibrary_Samraksh_SPOT_ADCInternal::GetData___STATIC__I4__SZARRAY_U2__U4__U4,
    Library_InterfaceLibrary_Samraksh_SPOT_ADCInternal::ConfigureBatchMode___STATIC__I4__SZARRAY_U2__U4__U4__U4__U4,
    Library_InterfaceLibrary_Samraksh_SPOT_ADCInternal::ConfigureContinuousMode___STATIC__I4__SZARRAY_U2__U4__U4__U4__U4,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_ADC =
{
    "Samraksh.SPOT.ADC", 
    0x8213AD2B,
    method_lookup
};

