//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SamrakshEmoteWLN.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::Init___STATIC__I4__I4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::Uninit___STATIC__BOOLEAN,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::Read___STATIC__R8__I4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::ConfigureBatchMode___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__I4__U4__U4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::ConfigureContinuousMode___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__I4__U4__U4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::ConfigureContinuousModeDualChannel___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::ConfigureBatchModeDualChannel___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::ConfigureContinuousModeWithThresholding___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__I4__U4__U4__U4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::ConfigureBatchModeWithThresholding___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__I4__U4__U4__U4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::DualChannelRead___STATIC__BOOLEAN__SZARRAY_U2,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::StopSampling___STATIC__I4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_ADCInternal::SetPeriodicADCSamplingInterval___STATIC__I4__R8__R8,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_NOR::InternalInitialize___STATIC__BOOLEAN,
    NULL,
    NULL,
    NULL,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_NOR::InternalWrite___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__U4__U2,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_NOR::InternalWrite___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__U4__U2__U2,
    NULL,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_NOR::InternalRead___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U2__U4__U2,
    NULL,
    NULL,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_SDInternal::InternalInitialize___STATIC__SamraksheMoteWLNDeviceStatus,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_SDInternal::InternalWrite___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U1__U2__U2__U4,
    Library_SamrakshEmoteWLN_Samraksh_eMote_WLN_SDInternal::InternalRead___STATIC__SamraksheMoteWLNDeviceStatus__SZARRAY_U1__U2__U2__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_WLN =
{
    "Samraksh_eMote_WLN", 
    0x65102C9D,
    method_lookup
};

