//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _INTERFACELIBRARY_H_
#define _INTERFACELIBRARY_H_

#include <TinyCLR_Interop.h>
struct Library_InterfaceLibrary_Samraksh_FileSystem
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__SamrakshFileSystemError);
    TINYCLR_NATIVE_DECLARE(Write___STATIC__SamrakshFileSystemError__SZARRAY_U1__U4__U2);
    TINYCLR_NATIVE_DECLARE(Read___STATIC__SamrakshFileSystemError__SZARRAY_U1__U4__U2);
    TINYCLR_NATIVE_DECLARE(Erase___STATIC__SamrakshFileSystemError__U4__U4);

    //--//

};

struct Library_InterfaceLibrary_Samraksh_Client
{
    static const int FIELD__m_id = 1;


    //--//

};

struct Library_InterfaceLibrary_Samraksh_MessageLayer
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(Send___STATIC__I4__SamrakshClient__U4__SZARRAY_U1__I4__SamrakshTime);
    TINYCLR_NATIVE_DECLARE(Received___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(ConfigureReceive___STATIC__I4);

    //--//

};

struct Library_InterfaceLibrary_Samraksh_TestCallback
{
    static const int FIELD__m_CallbackReceived = 5;
    static const int FIELD__m_CallbackRequired = 6;


    //--//

};

struct Library_InterfaceLibrary_Samraksh_Time
{
    static const int FIELD__m_time = 1;


    //--//

};

struct Library_InterfaceLibrary_Samraksh_TimeSync
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(setBeaconRate___STATIC__VOID__I4);
    TINYCLR_NATIVE_DECLARE(sendTimeSyncMessage___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(getLocalTime___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(getGlobalTime___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(getSkew___STATIC__R4);
    TINYCLR_NATIVE_DECLARE(local2Global___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(getRootId___STATIC__I2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh;

#endif  //_INTERFACELIBRARY_H_
