//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "InterfaceLibrary.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_InterfaceLibrary_Samraksh_FileSystem::Init___STATIC__SamrakshFileSystemError,
    Library_InterfaceLibrary_Samraksh_FileSystem::Write___STATIC__SamrakshFileSystemError__SZARRAY_U1__U4__U2,
    Library_InterfaceLibrary_Samraksh_FileSystem::Read___STATIC__SamrakshFileSystemError__SZARRAY_U1__U4__U2,
    Library_InterfaceLibrary_Samraksh_FileSystem::Erase___STATIC__SamrakshFileSystemError__U4__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_InterfaceLibrary_Samraksh_MessageLayer::Init___STATIC__I4,
    Library_InterfaceLibrary_Samraksh_MessageLayer::Send___STATIC__I4__SamrakshClient__U4__SZARRAY_U1__I4__SamrakshTime,
    Library_InterfaceLibrary_Samraksh_MessageLayer::Received___STATIC__I4,
    Library_InterfaceLibrary_Samraksh_MessageLayer::ConfigureReceive___STATIC__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_InterfaceLibrary_Samraksh_TimeSync::Init___STATIC__VOID,
    Library_InterfaceLibrary_Samraksh_TimeSync::setBeaconRate___STATIC__VOID__I4,
    Library_InterfaceLibrary_Samraksh_TimeSync::sendTimeSyncMessage___STATIC__VOID,
    Library_InterfaceLibrary_Samraksh_TimeSync::getLocalTime___STATIC__I4,
    Library_InterfaceLibrary_Samraksh_TimeSync::getGlobalTime___STATIC__I4,
    Library_InterfaceLibrary_Samraksh_TimeSync::getSkew___STATIC__R4,
    Library_InterfaceLibrary_Samraksh_TimeSync::local2Global___STATIC__VOID,
    Library_InterfaceLibrary_Samraksh_TimeSync::getRootId___STATIC__I2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh =
{
    "Samraksh", 
    0xB4B45E00,
    method_lookup
};

