//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSHEMOTEDOTLAURA_H_
#define _SAMRAKSHEMOTEDOTLAURA_H_

#include <TinyCLR_Interop.h>
struct Library_SamrakshEmoteDotLaura_Samraksh_eMote_DotLaura_LCD
{
    static const int FIELD__LCD_Initialized = 1;

    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(WriteString___VOID__SZARRAY_U1__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(Clear___VOID__I4__I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_DotLaura;

#endif  //_SAMRAKSHEMOTEDOTLAURA_H_
