//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SamrakshEmoteDotLaura.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_SamrakshEmoteDotLaura_Samraksh_eMote_DotLaura_LCD::Initialize___BOOLEAN,
    Library_SamrakshEmoteDotLaura_Samraksh_eMote_DotLaura_LCD::WriteString___VOID__SZARRAY_U1__I4__I4__I4,
    Library_SamrakshEmoteDotLaura_Samraksh_eMote_DotLaura_LCD::Clear___VOID__I4__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_DotLaura =
{
    "Samraksh_eMote_DotLaura", 
    0x76D2EC1F,
    method_lookup
};

