//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SamrakshEmoteAdapt.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_ADCInternal::Initialize___STATIC__I4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_ADCInternal::Read___STATIC__U4__SamraksheMoteAdaptAdcChannel,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_ADCInternal::ConfigureContinuousMode___STATIC__SamraksheMoteAdaptDeviceStatus__SZARRAY_U2__SamraksheMoteAdaptAdcChannel__U4__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_ADCInternal::StopSampling___STATIC__I4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_ADCInternal::GetMaxSampleRate___STATIC__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_ADCInternal::Uninitialize___STATIC__I4,
    NULL,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::Initialize___BOOLEAN,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::Reset___BOOLEAN,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::SelfTest___BOOLEAN,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::GetX___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::GetY___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::GetZ___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::GetTemperature___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::ReadRegister___U1__U1,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::WriteRegister___BOOLEAN__U1__U1,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::AdvancedConfiguration___BOOLEAN__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::SetPowerMode___BOOLEAN__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::SetBandwidth___BOOLEAN__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::SetRange___BOOLEAN__U1,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Accelerometer::GetAllData___BOOLEAN__SZARRAY_I2,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_FPGA::Initialize___BOOLEAN,
    NULL,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::Initialize___BOOLEAN,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::Reset___BOOLEAN,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::SelfTest___BOOLEAN,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::GetX___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::GetY___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::GetZ___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::GetTemperature___I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::ReadRegister___U1__U1,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::WriteRegister___BOOLEAN__U1__U1,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::AdvancedConfiguration___BOOLEAN__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::SetPowerMode___BOOLEAN__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::SetOffsets___BOOLEAN__I2__I2__I2,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::SampleConfiguration___BOOLEAN__U4,
    Library_SamrakshEmoteAdapt_Samraksh_eMote_Adapt_Gyroscope::GetAllData___BOOLEAN__SZARRAY_I2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_Adapt =
{
    "Samraksh_eMote_Adapt", 
    0x8405F623,
    method_lookup
};

