//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SPOT_NATIVE_H_
#define _SPOT_NATIVE_H_

#include <TinyCLR_Interop.h>
struct Library_spot_native_Samraksh_eMote_Adapt_Accelerometer
{
    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Reset___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SelfTest___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetX___I2);
    TINYCLR_NATIVE_DECLARE(GetY___I2);
    TINYCLR_NATIVE_DECLARE(GetZ___I2);
    TINYCLR_NATIVE_DECLARE(GetTemperature___I2);
    TINYCLR_NATIVE_DECLARE(ReadRegister___U1__U1);
    TINYCLR_NATIVE_DECLARE(WriteRegister___BOOLEAN__U1__U1);
    TINYCLR_NATIVE_DECLARE(AdvancedConfiguration___BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(SetPowerMode___BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(SetBandwidth___BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(SetRange___BOOLEAN__U1);
    TINYCLR_NATIVE_DECLARE(GetAllData___BOOLEAN__SZARRAY_I2);

    //--//

};

struct Library_spot_native_Samraksh_eMote_Adapt_AnalogInput
{
    TINYCLR_NATIVE_DECLARE(Initialize___SamraksheMoteAdaptDeviceStatus);
    TINYCLR_NATIVE_DECLARE(Read___U2__I4);
    TINYCLR_NATIVE_DECLARE(ReadBatch___SamraksheMoteAdaptDeviceStatus__SZARRAY_U2__I4__U4__U4);
    TINYCLR_NATIVE_DECLARE(GetMaxSampleRate___U4);

    //--//

};

struct Library_spot_native_Samraksh_eMote_Adapt_FPGA
{
    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);

    //--//

};

struct Library_spot_native_Samraksh_eMote_Adapt_Gyroscope
{
    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Reset___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SelfTest___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetX___I2);
    TINYCLR_NATIVE_DECLARE(GetY___I2);
    TINYCLR_NATIVE_DECLARE(GetZ___I2);
    TINYCLR_NATIVE_DECLARE(GetTemperature___I2);
    TINYCLR_NATIVE_DECLARE(ReadRegister___U1__U1);
    TINYCLR_NATIVE_DECLARE(WriteRegister___BOOLEAN__U1__U1);
    TINYCLR_NATIVE_DECLARE(AdvancedConfiguration___BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(SetPowerMode___BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(SetOffsets___BOOLEAN__I2__I2__I2);
    TINYCLR_NATIVE_DECLARE(SampleConfiguration___BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(GetAllData___BOOLEAN__SZARRAY_I2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_Adapt;

#endif  //_SPOT_NATIVE_H_
