//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_eMote_Net_Routing.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_eMote_Net_Routing_Samraksh_eMote_Net_Routing_RoutingLayer::SendRoutingData___STATIC__I4__SZARRAY_U1,
    Library_Samraksh_eMote_Net_Routing_Samraksh_eMote_Net_Routing_RoutingLayer::SendRoutingBeacon___STATIC__I4,
    Library_Samraksh_eMote_Net_Routing_Samraksh_eMote_Net_Routing_RoutingLayer::InitializeRouting___STATIC__I4__SZARRAY_U1__U2__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_Net_Routing =
{
    "Samraksh_eMote_Net_Routing", 
    0x73FD62E4,
    method_lookup
};

