//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _INTERFACELIBRARY_H_
#define _INTERFACELIBRARY_H_

#include <TinyCLR_Interop.h>
struct Library_InterfaceLibrary_Samraksh_TestCallback
{
    static const int FIELD__m_CallbackReceived = 5;
    static const int FIELD__m_CallbackRequired = 6;


    //--//

};

struct Library_InterfaceLibrary_Samraksh_TimeSync
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(setBeaconRate___STATIC__VOID__I4);
    TINYCLR_NATIVE_DECLARE(sendTimeSyncMessage___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(getLocalTime___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(getGlobalTime___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(getSkew___STATIC__R4);
    TINYCLR_NATIVE_DECLARE(local2Global___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(getRootId___STATIC__I2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh;

#endif  //_INTERFACELIBRARY_H_
