//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "InterfaceLibrary.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    Library_InterfaceLibrary_Samraksh_TimeSync::Init___STATIC__VOID,
    Library_InterfaceLibrary_Samraksh_TimeSync::setBeaconRate___STATIC__VOID__I4,
    Library_InterfaceLibrary_Samraksh_TimeSync::sendTimeSyncMessage___STATIC__VOID,
    Library_InterfaceLibrary_Samraksh_TimeSync::getLocalTime___STATIC__I4,
    Library_InterfaceLibrary_Samraksh_TimeSync::getGlobalTime___STATIC__I4,
    Library_InterfaceLibrary_Samraksh_TimeSync::getSkew___STATIC__R4,
    Library_InterfaceLibrary_Samraksh_TimeSync::local2Global___STATIC__VOID,
    Library_InterfaceLibrary_Samraksh_TimeSync::getRootId___STATIC__I2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh =
{
    "Samraksh", 
    0x95F5A405,
    method_lookup
};

