//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SamrakshEmoteSF2.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_SamrakshEmoteSF2_Samraksh_eMote_SF2_SPI::SendData___BOOLEAN__I4__SZARRAY_U1__I4,
    Library_SamrakshEmoteSF2_Samraksh_eMote_SF2_SPI::ReceiveData___BOOLEAN__I4__SZARRAY_U1__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_SF2 =
{
    "Samraksh_eMote_SF2", 
    0xE1E50A3C,
    method_lookup
};

