//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _AES_H_
#define _AES_H_

#include <TinyCLR_Interop.h>
struct Library_AES_MyEncryptionLib_SSL
{
    TINYCLR_NATIVE_DECLARE(encrypt___I4__STRING);
    TINYCLR_NATIVE_DECLARE(decrypt___I4__STRING);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MyEncryptionLib;

#endif  //_AES_H_
