//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_SPOT_NET_H_
#define _SAMRAKSH_SPOT_NET_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_CSMA
{
    static const int FIELD_STATIC__MyReceiveCallback = 0;
    static const int FIELD_STATIC__ReceiveMessage = 1;

    TINYCLR_NATIVE_DECLARE(Configure___SamrakshSPOTNetDeviceStatus__SamrakshSPOTNetMacMacConfiguration);
    TINYCLR_NATIVE_DECLARE(UnInitialize___SamrakshSPOTNetDeviceStatus);
    TINYCLR_NATIVE_DECLARE(Send___SamrakshSPOTNetNetOpStatus__U2__SZARRAY_U1__U2__U2);
    TINYCLR_NATIVE_DECLARE(GetAddress___U2);
    TINYCLR_NATIVE_DECLARE(SetAddress___BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(GetID___U1);
    TINYCLR_NATIVE_DECLARE(GetNeighborTable___SamrakshSPOTNetMacNeighborTable);
    TINYCLR_NATIVE_DECLARE(GetNeighbors___SamrakshSPOTNetMacNeighbor__U2);
    TINYCLR_NATIVE_DECLARE(GetBufferSize___U1);
    TINYCLR_NATIVE_DECLARE(GetPendingPacketCount___U1);
    TINYCLR_NATIVE_DECLARE(RemovePacket___SamrakshSPOTNetDeviceStatus__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(InternalInitialize___STATIC__SamrakshSPOTNetDeviceStatus__SamrakshSPOTNetMacMacConfiguration__SZARRAY_U1);

    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_Link
{
    static const int FIELD__Quality = 1;
    static const int FIELD__LossRate = 2;
    static const int FIELD__AveDelay = 3;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_MacConfiguration
{
    static const int FIELD__CCA = 1;
    static const int FIELD__NumberOfRetries = 2;
    static const int FIELD__CCASenseTime = 3;
    static const int FIELD__BufferSize = 4;
    static const int FIELD__RadioID = 5;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_Neighbor
{
    static const int FIELD__MacAddress = 1;
    static const int FIELD__ForwardLink = 2;
    static const int FIELD__ReverseLink = 3;
    static const int FIELD__Status = 4;
    static const int FIELD__LastHeardTime = 5;
    static const int FIELD__ReceiveDutyCycle = 6;
    static const int FIELD__FrameLength = 7;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_NeighborTable
{
    static const int FIELD__NumberValidNeighbor = 1;
    static const int FIELD__Neighbor = 2;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Radio_RadioConfiguration
{
    static const int FIELD__TxPower = 1;
    static const int FIELD__Sensitivity = 2;
    static const int FIELD__Channel = 3;
    static const int FIELD__TimeStampOffset = 4;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Radio_Radio_802_15_4
{
    static const int FIELD_STATIC__MyReceiveCallback = 2;
    static const int FIELD_STATIC__ReceiveMessage = 3;

    TINYCLR_NATIVE_DECLARE(Configure___SamrakshSPOTNetDeviceStatus__SamrakshSPOTNetRadioRadioConfiguration);
    TINYCLR_NATIVE_DECLARE(UnInitialize___SamrakshSPOTNetDeviceStatus);
    TINYCLR_NATIVE_DECLARE(GetID___U1);
    TINYCLR_NATIVE_DECLARE(GetAddress___U2);
    TINYCLR_NATIVE_DECLARE(SetAddress___BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(TurnOn___SamrakshSPOTNetDeviceStatus);
    TINYCLR_NATIVE_DECLARE(Sleep___SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(PreLoad___SamrakshSPOTNetNetOpStatus__SZARRAY_U1__U2);
    TINYCLR_NATIVE_DECLARE(SendStrobe___SamrakshSPOTNetNetOpStatus);
    TINYCLR_NATIVE_DECLARE(Send___SamrakshSPOTNetNetOpStatus__SZARRAY_U1__U2);
    TINYCLR_NATIVE_DECLARE(SendTimeStamped___SamrakshSPOTNetNetOpStatus__SZARRAY_U1__U2__U4);
    TINYCLR_NATIVE_DECLARE(ClearChannelAssesment___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(ClearChannelAssesment___BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(InternalInitialize___STATIC__SamrakshSPOTNetDeviceStatus__SamrakshSPOTNetRadioRadioConfiguration__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_Net;

#endif  //_SAMRAKSH_SPOT_NET_H_
