//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_SPOT_NET_H_
#define _SAMRAKSH_SPOT_NET_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_MACBase
{
    static const int FIELD__message = 5;
    static const int FIELD__ByteNeighbor = 6;
    static const int FIELD__MarshalBuffer = 7;
    static const int FIELD__MyReceiveCallback = 8;

    TINYCLR_NATIVE_DECLARE(RemovePacket___SamrakshSPOTNetDeviceStatus__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(GetPendingPacketCount___U1);
    TINYCLR_NATIVE_DECLARE(GetBufferSize___U1);
    TINYCLR_NATIVE_DECLARE(GetID___U1);
    TINYCLR_NATIVE_DECLARE(SetAddress___BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(GetAddress___U2);
    TINYCLR_NATIVE_DECLARE(Send___SamrakshSPOTNetNetOpStatus__U2__SZARRAY_U1__U2__U2);
    TINYCLR_NATIVE_DECLARE(UnInitialize___SamrakshSPOTNetDeviceStatus);
    TINYCLR_NATIVE_DECLARE(Configure___SamrakshSPOTNetDeviceStatus__SamrakshSPOTNetMacMacConfiguration);
    TINYCLR_NATIVE_DECLARE(SetCCA___SamrakshSPOTNetDeviceStatus__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SetNumberOfRetries___SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(SetCCASenseTime___SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(SetBufferSize___SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(SetRadioID___SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(GetCCA___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetNumberOfRetries___U1);
    TINYCLR_NATIVE_DECLARE(GetCCASenseTime___U1);
    TINYCLR_NATIVE_DECLARE(GetRadioID___U1);
    TINYCLR_NATIVE_DECLARE(InternalInitialize___SamrakshSPOTNetDeviceStatus__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(GetNeighborInternal___BOOLEAN__U2__SZARRAY_U1);

    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_CSMA
{
    static const int FIELD_STATIC__instance = 0;
    static const int FIELD_STATIC__syncObject = 1;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_CSMAOld
{
    static const int FIELD_STATIC__MyReceiveCallback = 2;
    static const int FIELD_STATIC__RSSI = 3;
    static const int FIELD_STATIC__LinkQuality = 4;
    static const int FIELD_STATIC__Src = 5;
    static const int FIELD_STATIC__Unicast = 6;
    static const int FIELD_STATIC__ReceiveMessage = 7;
    static const int FIELD_STATIC__ByteNeighbor = 8;
    static const int FIELD_STATIC__MarshalBuffer = 9;

    TINYCLR_NATIVE_DECLARE(Configure___SamrakshSPOTNetDeviceStatus__SamrakshSPOTNetMacMacConfiguration);
    TINYCLR_NATIVE_DECLARE(UnInitialize___SamrakshSPOTNetDeviceStatus);
    TINYCLR_NATIVE_DECLARE(Send___SamrakshSPOTNetNetOpStatus__U2__SZARRAY_U1__U2__U2);
    TINYCLR_NATIVE_DECLARE(GetAddress___U2);
    TINYCLR_NATIVE_DECLARE(SetAddress___BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(GetID___U1);
    TINYCLR_NATIVE_DECLARE(GetBufferSize___U1);
    TINYCLR_NATIVE_DECLARE(GetPendingPacketCount___U1);
    TINYCLR_NATIVE_DECLARE(RemovePacket___SamrakshSPOTNetDeviceStatus__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(GetNeighborInternal___BOOLEAN__U2__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(SetCCA___STATIC__SamrakshSPOTNetDeviceStatus__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SetNumberOfRetries___STATIC__SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(SetCCASenseTime___STATIC__SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(SetBufferSize___STATIC__SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(SetRadioID___STATIC__SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(GetCCA___STATIC__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetNumberOfRetries___STATIC__U1);
    TINYCLR_NATIVE_DECLARE(GetCCASenseTime___STATIC__U1);
    TINYCLR_NATIVE_DECLARE(GetRadioID___STATIC__U1);
    TINYCLR_NATIVE_DECLARE(ReConfigure___STATIC__SamrakshSPOTNetDeviceStatus__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(InternalInitialize___STATIC__SamrakshSPOTNetDeviceStatus__SamrakshSPOTNetMacMacConfiguration__SZARRAY_U1);

    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_Link
{
    static const int FIELD__AveRSSI = 1;
    static const int FIELD__LinkQuality = 2;
    static const int FIELD__AveDelay = 3;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_MacConfiguration
{
    static const int FIELD__CCA = 1;
    static const int FIELD__NumberOfRetries = 2;
    static const int FIELD__CCASenseTime = 3;
    static const int FIELD__BufferSize = 4;
    static const int FIELD__RadioID = 5;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_Neighbor
{
    static const int FIELD__MacAddress = 1;
    static const int FIELD__ForwardLink = 2;
    static const int FIELD__ReverseLink = 3;
    static const int FIELD__Status = 4;
    static const int FIELD__PacketsReceived = 5;
    static const int FIELD__LastHeardTime = 6;
    static const int FIELD__ReceiveDutyCycle = 7;
    static const int FIELD__FrameLength = 8;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Mac_NeighborTable
{
    static const int FIELD__NumberValidNeighbor = 1;
    static const int FIELD__Neighbor = 2;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Message
{
    static const int FIELD__RSSI = 1;
    static const int FIELD__LQI = 2;
    static const int FIELD__Src = 3;
    static const int FIELD__Unicast = 4;
    static const int FIELD__ReceiveMessage = 5;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Radio_RadioConfiguration
{
    static const int FIELD__TxPower = 1;
    static const int FIELD__Channel = 2;


    //--//

};

struct Library_Samraksh_SPOT_Net_Samraksh_SPOT_Net_Radio_Radio_802_15_4
{
    static const int FIELD_STATIC__MyReceiveCallback = 10;
    static const int FIELD_STATIC__config = 11;
    static const int FIELD_STATIC__instance = 12;
    static const int FIELD_STATIC__syncObject = 13;

    static const int FIELD__dataBuffer = 5;
    static const int FIELD__message = 6;
    static const int FIELD__marshalBuffer = 7;

    TINYCLR_NATIVE_DECLARE(UnInitialize___SamrakshSPOTNetDeviceStatus);
    TINYCLR_NATIVE_DECLARE(GetID___U1);
    TINYCLR_NATIVE_DECLARE(GetAddress___U2);
    TINYCLR_NATIVE_DECLARE(SetAddress___BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(TurnOn___SamrakshSPOTNetDeviceStatus);
    TINYCLR_NATIVE_DECLARE(Sleep___SamrakshSPOTNetDeviceStatus__U1);
    TINYCLR_NATIVE_DECLARE(PreLoad___SamrakshSPOTNetNetOpStatus__SZARRAY_U1__U2);
    TINYCLR_NATIVE_DECLARE(SendStrobe___SamrakshSPOTNetNetOpStatus);
    TINYCLR_NATIVE_DECLARE(Send___SamrakshSPOTNetNetOpStatus__SZARRAY_U1__U2);
    TINYCLR_NATIVE_DECLARE(SendTimeStamped___SamrakshSPOTNetNetOpStatus__SZARRAY_U1__U2__U4);
    TINYCLR_NATIVE_DECLARE(ClearChannelAssesment___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(ClearChannelAssesment___BOOLEAN__U2);
    TINYCLR_NATIVE_DECLARE(GetNextPacket___SamrakshSPOTNetDeviceStatus__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(InternalInitialize___SamrakshSPOTNetDeviceStatus__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(SetTxPower___SamrakshSPOTNetDeviceStatus__I4);
    TINYCLR_NATIVE_DECLARE(SetChannel___SamrakshSPOTNetDeviceStatus__I4);
    TINYCLR_NATIVE_DECLARE(GetTxPower___I4);
    TINYCLR_NATIVE_DECLARE(GetChannel___I4);
    TINYCLR_NATIVE_DECLARE(ReConfigure___SamrakshSPOTNetDeviceStatus__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_Net;

#endif  //_SAMRAKSH_SPOT_NET_H_
