//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Lib.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_Lib_SimpleInterop_Library::init___VOID,
    Library_Lib_SimpleInterop_Library::execute___VOID,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SimpleInterop =
{
    "SimpleInterop", 
    0x940D9378,
    method_lookup
};

