//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _LIB_H_
#define _LIB_H_

#include <TinyCLR_Interop.h>
struct Library_Lib_SimpleInterop_Library
{
    TINYCLR_NATIVE_DECLARE(init___VOID);
    TINYCLR_NATIVE_DECLARE(execute___VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SimpleInterop;

#endif  //_LIB_H_
