//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SPOT_NATIVE_H_
#define _SPOT_NATIVE_H_

#include <TinyCLR_Interop.h>
struct Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_LCD
{
    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Write___BOOLEAN__I4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(Clear___BOOLEAN);

    //--//

};

struct Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_AnalogInput
{
    TINYCLR_NATIVE_DECLARE(Read___R8);
    TINYCLR_NATIVE_DECLARE(ReadRaw___I4);
    TINYCLR_NATIVE_DECLARE(Dispose___VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_Hardware;

#endif  //_SPOT_NATIVE_H_
