//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "spot_native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::Init___STATIC__I4__I4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::Read___STATIC__R8__I4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::ConfigureBatchMode___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__I4__U4__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::ConfigureContinuousMode___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__I4__U4__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::ConfigureContinuousModeDualChannel___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::ConfigureBatchModeDualChannel___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::ConfigureContinuousModeWithThresholding___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__I4__U4__U4__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::ConfigureBatchModeWithThresholding___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__I4__U4__U4__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::DualChannelRead___STATIC__BOOLEAN__SZARRAY_U2,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_ADCInternal::StopSampling___STATIC__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::Initialize___BOOLEAN,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::Uninitialize___BOOLEAN,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::Write___BOOLEAN__SamrakshSPOTHardwareEmoteDotNowLCD__SamrakshSPOTHardwareEmoteDotNowLCD__SamrakshSPOTHardwareEmoteDotNowLCD__SamrakshSPOTHardwareEmoteDotNowLCD,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::SetDP___BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::WriteN___BOOLEAN__I4__SamrakshSPOTHardwareEmoteDotNowLCD,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::WriteRawBytes___BOOLEAN__I4__I4__I4__I4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::Blink___BOOLEAN__SamrakshSPOTHardwareEmoteDotNowBlink,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_EmoteLCD::Clear___BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_NOR::InternalInitialize___STATIC__BOOLEAN,
    NULL,
    NULL,
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_NOR::InternalWrite___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__U4__U2,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_NOR::InternalWrite___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__U4__U2__U2,
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_NOR::InternalRead___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U2__U4__U2,
    NULL,
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_SDInternal::InternalInitialize___STATIC__SamrakshSPOTHardwareDeviceStatus,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_SDInternal::InternalWrite___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U1__U2__U2__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_EmoteDotNow_SDInternal::InternalRead___STATIC__SamrakshSPOTHardwareDeviceStatus__SZARRAY_U1__U2__U2__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_Hardware =
{
    "Samraksh_SPOT_Hardware", 
    0x72BF0A05,
    method_lookup
};

