//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Library.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    Library_Library_Samraksh_SPOT_USB::Write___STATIC__I4__SZARRAY_U1__I4__I4,
    Library_Library_Samraksh_SPOT_USB::Read___STATIC__I4__SZARRAY_U1__I4__I4,
    Library_Library_Samraksh_SPOT_USB::Flush___STATIC__BOOLEAN,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_USB =
{
    "Samraksh.SPOT.USB", 
    0x71C9893A,
    method_lookup
};

