//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _LIBRARY_H_
#define _LIBRARY_H_

#include <TinyCLR_Interop.h>
struct Library_Library_Samraksh_SPOT_USB
{
    TINYCLR_NATIVE_DECLARE(Write___STATIC__I4__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(Read___STATIC__I4__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(Flush___STATIC__BOOLEAN);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_USB;

#endif  //_LIBRARY_H_
