//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Library.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_Library_TinyOS_TinyosInterface::execute___VOID__SZARRAY_U1,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_TinyOS =
{
    "TinyOS", 
    0xEC23349D,
    method_lookup
};

