//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _LIBRARY_H_
#define _LIBRARY_H_

#include <TinyCLR_Interop.h>
struct Library_Library_TinyOS_TinyosInterface
{
    TINYCLR_NATIVE_DECLARE(execute___VOID__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_TinyOS;

#endif  //_LIBRARY_H_
