//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "spot_native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_Init___BOOLEAN,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_Reset___BOOLEAN,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_SelfTest___BOOLEAN,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_GetX___I2,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_GetY___I2,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_GetZ___I2,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_GetTemperature___I2,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_Raw_Read___U1__U1,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_Raw_Write___BOOLEAN__U1__U1,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_advconfig___BOOLEAN__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_SetPowerMode___BOOLEAN__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_SetBandwidth___BOOLEAN__U4,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_SetBandwidth___BOOLEAN__U1,
    Library_spot_native_Samraksh_SPOT_Hardware_Adapt_Accelerometer::ADAPT_Accel_GetAll___BOOLEAN__SZARRAY_I2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_Hardware_Adapt =
{
    "Samraksh_SPOT_Hardware_Adapt", 
    0x86FA656B,
    method_lookup
};

