//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "spot_native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_spot_native_Samraksh_SPOT_Hardware_Accelerometer::ADAPT_Accel_Init___BOOLEAN,
    Library_spot_native_Samraksh_SPOT_Hardware_Accelerometer::ADAPT_Accel_GetX___I4,
    Library_spot_native_Samraksh_SPOT_Hardware_Accelerometer::ADAPT_Accel_GetY___I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_Hardware =
{
    "Samraksh_SPOT_Hardware", 
    0xB9D009CA,
    method_lookup
};

