//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSHEMOTESF2_H_
#define _SAMRAKSHEMOTESF2_H_

#include <TinyCLR_Interop.h>
struct Library_SamrakshEmoteSF2_Samraksh_eMote_SF2_SPI
{
    TINYCLR_NATIVE_DECLARE(SendData___BOOLEAN__I4__SZARRAY_U1__I4);
    TINYCLR_NATIVE_DECLARE(ReceiveData___BOOLEAN__I4__SZARRAY_U1__I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_SF2;

#endif  //_SAMRAKSHEMOTESF2_H_
