//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "KiwiSensorBoard.h"
#include "KiwiSensorBoard_Samraksh_eMote_SensorBoard_Buzzer.h"

using namespace Samraksh::eMote::SensorBoard;


HRESULT Library_KiwiSensorBoard_Samraksh_eMote_SensorBoard_Buzzer::On___STATIC__BOOLEAN( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        INT8 retVal = Buzzer::On( hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT8( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_KiwiSensorBoard_Samraksh_eMote_SensorBoard_Buzzer::Off___STATIC__BOOLEAN( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        INT8 retVal = Buzzer::Off( hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_INT8( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}
