//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _KIWISENSORBOARD_H_
#define _KIWISENSORBOARD_H_

#include <TinyCLR_Interop.h>
struct Library_KiwiSensorBoard_Samraksh_eMote_Kiwi_Accelerometer
{
    static const int FIELD__accelDataBuffer = 1;
    static const int FIELD__refreshRate = 2;
    static const int FIELD__config = 3;
    static const int FIELD__i2cdevice = 4;
    static const int FIELD__currentRange = 5;
    static const int FIELD__currentResolution = 6;
    static const int FIELD__sensorData = 7;
    static const int FIELD__sensorSamplingTimer = 8;
    static const int FIELD__userCallbackFn = 9;
    static const int FIELD__writeAccelDataBuffer = 10;
    static const int FIELD__readAccelDataBuffer = 11;
    static const int FIELD__getAccelDataTransaction = 12;


    //--//

};

struct Library_KiwiSensorBoard_Samraksh_eMote_Kiwi_TemperatureSensor
{
    static const int FIELD__m_pin = 1;
    static const int FIELD__m_oneWire = 2;
    static const int FIELD__m_devices = 3;
    static const int FIELD__m_samplingTimer = 4;
    static const int FIELD__temperature = 5;
    static const int FIELD__lockTemperature = 6;


    //--//

};

struct Library_KiwiSensorBoard_Samraksh_eMote_Kiwi_Accelerometer__Data
{
    static const int FIELD__RawX = 1;
    static const int FIELD__RawY = 2;
    static const int FIELD__RawZ = 3;
    static const int FIELD__X = 4;
    static const int FIELD__Y = 5;
    static const int FIELD__Z = 6;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_Kiwi;

#endif  //_KIWISENSORBOARD_H_
