//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _INTERFACELIBRARY_H_
#define _INTERFACELIBRARY_H_

#include <TinyCLR_Interop.h>
struct Library_InterfaceLibrary_Samraksh_FileSystem
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__SamrakshFileSystemError);
    TINYCLR_NATIVE_DECLARE(Write___STATIC__SamrakshFileSystemError__SZARRAY_U1__U4__U2);
    TINYCLR_NATIVE_DECLARE(Read___STATIC__SamrakshFileSystemError__SZARRAY_U1__U4__U2);
    TINYCLR_NATIVE_DECLARE(Erase___STATIC__SamrakshFileSystemError__U4__U4);

    //--//

};

struct Library_InterfaceLibrary_Samraksh_MessageLayer
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(Send___STATIC__I4__U1__U2__SZARRAY_U1__U2);
    TINYCLR_NATIVE_DECLARE(Received___STATIC__I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(ConfigureReceiver___STATIC__I4__U1__SamrakshMessageLayerRadioCallBack);

    //--//

};

struct Library_InterfaceLibrary_Samraksh_ADC
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__I4__I4);
    TINYCLR_NATIVE_DECLARE(getData___STATIC__I4__SZARRAY_U2__U4__U4);

    //--//

};

struct Library_InterfaceLibrary_Samraksh_Memory
{
    static const int FIELD_STATIC__currentRecordId = 0;

    static const int FIELD__recordId = 1;
    static const int FIELD__buffer = 2;

    TINYCLR_NATIVE_DECLARE(write___BOOLEAN__I4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(constructNativeMemoryPointer___BOOLEAN__I4__U4);
    TINYCLR_NATIVE_DECLARE(disposeNativeMemoryPointer___BOOLEAN__I4);
    TINYCLR_NATIVE_DECLARE(read___BOOLEAN__I4__SZARRAY_U1);

    //--//

};

struct Library_InterfaceLibrary_Samraksh_TestCallback
{
    static const int FIELD__m_CallbackReceived = 5;
    static const int FIELD__m_CallbackRequired = 6;


    //--//

};

struct Library_InterfaceLibrary_Samraksh_Time
{
    static const int FIELD__m_time = 1;


    //--//

};

struct Library_InterfaceLibrary_Samraksh_TimeSync
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(setBeaconRate___STATIC__VOID__I4);
    TINYCLR_NATIVE_DECLARE(sendTimeSyncMessage___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(getLocalTime___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(getGlobalTime___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(getSkew___STATIC__R4);
    TINYCLR_NATIVE_DECLARE(local2Global___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(getRootId___STATIC__I2);

    //--//

};

struct Library_InterfaceLibrary_Samraksh_rDAC
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(setValue___STATIC__I4__U2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh;

#endif  //_INTERFACELIBRARY_H_
