//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSHEMOTEDOTNOW_H_
#define _SAMRAKSHEMOTEDOTNOW_H_

#include <TinyCLR_Interop.h>
struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_SD
{
    static const int FIELD_STATIC__sdInternalObject = 0;
    static const int FIELD_STATIC__sdCallbackFunction = 1;
    static const int FIELD_STATIC__writeAddressPtr = 2;
    static const int FIELD_STATIC__readAddressPtr = 3;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__I4__I4);
    TINYCLR_NATIVE_DECLARE(Uninit___STATIC__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Read___STATIC__R8__I4);
    TINYCLR_NATIVE_DECLARE(ConfigureBatchMode___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureContinuousMode___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureContinuousModeDualChannel___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureBatchModeDualChannel___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureContinuousModeWithThresholding___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureBatchModeWithThresholding___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4__U4);
    TINYCLR_NATIVE_DECLARE(DualChannelRead___STATIC__BOOLEAN__SZARRAY_U2);
    TINYCLR_NATIVE_DECLARE(StopSampling___STATIC__I4);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_AnalogInput
{
    static const int FIELD_STATIC___adcInternal = 4;
    static const int FIELD_STATIC___myCallback = 5;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_EmoteLCD
{
    static const int FIELD__currentColumn1 = 1;
    static const int FIELD__currentColumn2 = 2;
    static const int FIELD__currentColumn3 = 3;
    static const int FIELD__currentColumn4 = 4;
    static const int FIELD__DP1 = 5;
    static const int FIELD__DP2 = 6;
    static const int FIELD__DP3 = 7;
    static const int FIELD__DP4 = 8;

    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Uninitialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Write___BOOLEAN__SamraksheMoteDotNowLCD__SamraksheMoteDotNowLCD__SamraksheMoteDotNowLCD__SamraksheMoteDotNowLCD);
    TINYCLR_NATIVE_DECLARE(SetDP___BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(WriteN___BOOLEAN__I4__SamraksheMoteDotNowLCD);
    TINYCLR_NATIVE_DECLARE(WriteRawBytes___BOOLEAN__I4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(Blink___BOOLEAN__SamraksheMoteDotNowBlink);
    TINYCLR_NATIVE_DECLARE(Clear___BOOLEAN);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NOR
{
    static const int FIELD_STATIC__writeAddressPtr = 6;
    static const int FIELD_STATIC__readAddressPtr = 7;
    static const int FIELD_STATIC__startOfRecordDelimiter = 8;
    static const int FIELD_STATIC__endOfRecordDelimiter = 9;
    static const int FIELD_STATIC__startOfRecordInBytes = 10;
    static const int FIELD_STATIC__endOfRecordInBytes = 11;
    static const int FIELD_STATIC__maxSize = 12;
    static const int FIELD_STATIC__fullFlag = 13;

    TINYCLR_NATIVE_DECLARE(InternalInitialize___STATIC__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2);
    TINYCLR_NATIVE_DECLARE(InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2__U2);
    TINYCLR_NATIVE_DECLARE(InternalRead___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_SDInternal
{
    TINYCLR_NATIVE_DECLARE(InternalInitialize___STATIC__SamraksheMoteDotNowDeviceStatus);
    TINYCLR_NATIVE_DECLARE(InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U1__U2__U2__U4);
    TINYCLR_NATIVE_DECLARE(InternalRead___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U1__U2__U2__U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_DotNow;

#endif  //_SAMRAKSHEMOTEDOTNOW_H_
