//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSHEMOTEDOTNOW_H_
#define _SAMRAKSHEMOTEDOTNOW_H_

#include <TinyCLR_Interop.h>
struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_FileSystemManager
{
    static const int FIELD_STATIC__m_openFiles = 0;
    static const int FIELD_STATIC__m_lockedDirs = 1;
    static const int FIELD_STATIC__CurrentDirectory = 2;
    static const int FIELD_STATIC__m_currentDirectoryRecord = 3;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_FileSystemManager__FileRecord
{
    static const int FIELD__FullName = 1;
    static const int FIELD__NativeFileStream = 2;
    static const int FIELD__Share = 3;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_SD
{
    static const int FIELD_STATIC__sdInternalObject = 4;
    static const int FIELD_STATIC__sdCallbackFunction = 5;
    static const int FIELD_STATIC__writeAddressPtr = 6;
    static const int FIELD_STATIC__readAddressPtr = 7;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal
{
    TINYCLR_NATIVE_DECLARE(Init___STATIC__I4__I4);
    TINYCLR_NATIVE_DECLARE(Read___STATIC__R8__I4);
    TINYCLR_NATIVE_DECLARE(ConfigureBatchMode___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureContinuousMode___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureContinuousModeDualChannel___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureBatchModeDualChannel___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureContinuousModeWithThresholding___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4__U4);
    TINYCLR_NATIVE_DECLARE(ConfigureBatchModeWithThresholding___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4__U4);
    TINYCLR_NATIVE_DECLARE(DualChannelRead___STATIC__BOOLEAN__SZARRAY_U2);
    TINYCLR_NATIVE_DECLARE(StopSampling___STATIC__I4);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_AnalogInput
{
    static const int FIELD_STATIC___adcInternal = 8;
    static const int FIELD_STATIC___myCallback = 9;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_EmoteLCD
{
    static const int FIELD__currentColumn1 = 1;
    static const int FIELD__currentColumn2 = 2;
    static const int FIELD__currentColumn3 = 3;
    static const int FIELD__currentColumn4 = 4;
    static const int FIELD__DP1 = 5;
    static const int FIELD__DP2 = 6;
    static const int FIELD__DP3 = 7;
    static const int FIELD__DP4 = 8;

    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Uninitialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Write___BOOLEAN__SamraksheMoteDotNowLCD__SamraksheMoteDotNowLCD__SamraksheMoteDotNowLCD__SamraksheMoteDotNowLCD);
    TINYCLR_NATIVE_DECLARE(SetDP___BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(WriteN___BOOLEAN__I4__SamraksheMoteDotNowLCD);
    TINYCLR_NATIVE_DECLARE(WriteRawBytes___BOOLEAN__I4__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(Blink___BOOLEAN__SamraksheMoteDotNowBlink);
    TINYCLR_NATIVE_DECLARE(Clear___BOOLEAN);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_MediaEventArgs
{
    static const int FIELD__Time = 1;
    static const int FIELD__Volume = 2;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NOR
{
    static const int FIELD_STATIC__writeAddressPtr = 10;
    static const int FIELD_STATIC__readAddressPtr = 11;
    static const int FIELD_STATIC__startOfRecordDelimiter = 12;
    static const int FIELD_STATIC__endOfRecordDelimiter = 13;
    static const int FIELD_STATIC__startOfRecordInBytes = 14;
    static const int FIELD_STATIC__endOfRecordInBytes = 15;
    static const int FIELD_STATIC__maxSize = 16;
    static const int FIELD_STATIC__fullFlag = 17;

    TINYCLR_NATIVE_DECLARE(InternalInitialize___STATIC__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2);
    TINYCLR_NATIVE_DECLARE(InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2__U2);
    TINYCLR_NATIVE_DECLARE(InternalRead___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NativeFileInfo
{
    static const int FIELD__Attributes = 1;
    static const int FIELD__CreationTime = 2;
    static const int FIELD__LastAccessTime = 3;
    static const int FIELD__LastWriteTime = 4;
    static const int FIELD__Size = 5;
    static const int FIELD__FileName = 6;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NativeFileStream
{
    static const int FIELD__m_fs = 1;

    TINYCLR_NATIVE_DECLARE(_ctor___VOID__STRING__I4);
    TINYCLR_NATIVE_DECLARE(Read___I4__SZARRAY_U1__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(Write___I4__SZARRAY_U1__I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(Seek___I8__I8__U4);
    TINYCLR_NATIVE_DECLARE(Flush___VOID);
    TINYCLR_NATIVE_DECLARE(GetLength___I8);
    TINYCLR_NATIVE_DECLARE(SetLength___VOID__I8);
    TINYCLR_NATIVE_DECLARE(GetStreamProperties___VOID__BYREF_BOOLEAN__BYREF_BOOLEAN__BYREF_BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Close___VOID);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NativeFindFile
{
    static const int FIELD__m_ff = 1;

    TINYCLR_NATIVE_DECLARE(_ctor___VOID__STRING__STRING);
    TINYCLR_NATIVE_DECLARE(GetNext___SamraksheMoteDotNowNativeFileInfo);
    TINYCLR_NATIVE_DECLARE(Close___VOID);
    TINYCLR_NATIVE_DECLARE(GetFileInfo___STATIC__SamraksheMoteDotNowNativeFileInfo__STRING);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NativeIO
{
    TINYCLR_NATIVE_DECLARE(Format___STATIC__VOID__STRING__STRING__STRING__U4);
    TINYCLR_NATIVE_DECLARE(Delete___STATIC__VOID__STRING);
    TINYCLR_NATIVE_DECLARE(Move___STATIC__BOOLEAN__STRING__STRING);
    TINYCLR_NATIVE_DECLARE(CreateDirectory___STATIC__VOID__STRING);
    TINYCLR_NATIVE_DECLARE(GetAttributes___STATIC__U4__STRING);
    TINYCLR_NATIVE_DECLARE(SetAttributes___STATIC__VOID__STRING__U4);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_RemovableMedia
{
    static const int FIELD_STATIC__Insert = 18;
    static const int FIELD_STATIC__Eject = 19;
    static const int FIELD_STATIC___volumes = 20;
    static const int FIELD_STATIC___events = 21;

    TINYCLR_NATIVE_DECLARE(MountRemovableVolumes___STATIC__VOID);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_SDInternal
{
    TINYCLR_NATIVE_DECLARE(InternalInitialize___STATIC__SamraksheMoteDotNowDeviceStatus);
    TINYCLR_NATIVE_DECLARE(InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U1__U2__U2__U4);
    TINYCLR_NATIVE_DECLARE(InternalRead___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U1__U2__U2__U4);

    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_StorageEvent
{
    static const int FIELD__EventType = 3;
    static const int FIELD__Handle = 4;
    static const int FIELD__Time = 5;


    //--//

};

struct Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_VolumeInfo
{
    static const int FIELD___Name = 1;
    static const int FIELD__VolumeLabel = 2;
    static const int FIELD__VolumeID = 3;
    static const int FIELD__FileSystem = 4;
    static const int FIELD__FileSystemFlags = 5;
    static const int FIELD__DeviceFlags = 6;
    static const int FIELD__SerialNumber = 7;
    static const int FIELD__TotalFreeSpace = 8;
    static const int FIELD__TotalSize = 9;
    static const int FIELD__VolumePtr = 10;

    TINYCLR_NATIVE_DECLARE(_ctor___VOID__STRING);
    TINYCLR_NATIVE_DECLARE(_ctor___VOID__U4);
    TINYCLR_NATIVE_DECLARE(Refresh___VOID);
    TINYCLR_NATIVE_DECLARE(FlushAll___VOID);
    TINYCLR_NATIVE_DECLARE(GetName___STRING);
    TINYCLR_NATIVE_DECLARE(GetVolumes___STATIC__SZARRAY_SamraksheMoteDotNowVolumeInfo);
    TINYCLR_NATIVE_DECLARE(GetFileSystems___STATIC__SZARRAY_STRING);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_DotNow;

#endif  //_SAMRAKSHEMOTEDOTNOW_H_
