//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SamrakshEmoteDotNow.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::Init___STATIC__I4__I4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::Uninit___STATIC__BOOLEAN,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::Read___STATIC__R8__I4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::ConfigureBatchMode___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::ConfigureContinuousMode___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::ConfigureContinuousModeDualChannel___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::ConfigureBatchModeDualChannel___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__SZARRAY_U2__U4__U4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::ConfigureContinuousModeWithThresholding___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4__U4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::ConfigureBatchModeWithThresholding___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__I4__U4__U4__U4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::DualChannelRead___STATIC__BOOLEAN__SZARRAY_U2,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_ADCInternal::StopSampling___STATIC__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NOR::InternalInitialize___STATIC__BOOLEAN,
    NULL,
    NULL,
    NULL,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NOR::InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NOR::InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2__U2,
    NULL,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_NOR::InternalRead___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U2__U4__U2,
    NULL,
    NULL,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_SDInternal::InternalInitialize___STATIC__SamraksheMoteDotNowDeviceStatus,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_SDInternal::InternalWrite___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U1__U2__U2__U4,
    Library_SamrakshEmoteDotNow_Samraksh_eMote_DotNow_SDInternal::InternalRead___STATIC__SamraksheMoteDotNowDeviceStatus__SZARRAY_U1__U2__U2__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_DotNow =
{
    "Samraksh_eMote_DotNow", 
    0xF461E43C,
    method_lookup
};

