//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_EMOTE_DIRECT_H_
#define _SAMRAKSH_EMOTE_DIRECT_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_Emote_Direct_Samraksh_Emote_Direct_Static
{
    TINYCLR_NATIVE_DECLARE(SetJump___U4__U4);
    TINYCLR_NATIVE_DECLARE(RunNative___VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_Emote_Direct;

#endif  //_SAMRAKSH_EMOTE_DIRECT_H_
