//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_Emote_Direct.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_Samraksh_Emote_Direct_Samraksh_Emote_Direct_Static::SetJump___U4__U4,
    Library_Samraksh_Emote_Direct_Samraksh_Emote_Direct_Static::RunNative___VOID,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_Emote_Direct =
{
    "Samraksh_Emote_Direct", 
    0x0594D4C7,
    method_lookup
};

