//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "ADC.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_ADC_ADC_library_ADC::initialize___BOOLEAN,
    Library_ADC_ADC_library_ADC::getData___I4,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_ADC_library =
{
    "ADC_library", 
    0xA0DDFC9F,
    method_lookup
};

